### PR TITLE
Make build script not run if derived optics have not changed

### PR DESCRIPTION
**Pull request by maackle**
Attempting to address #11 with this PR. I'm not sure that this is 100% right in all situations, but it works well for me on a large project with multiple crates in a long dependency chain where multiple crates depend on lens-rs. I would want to try various things to see if this can break, i.e. see if it doesn't pick up changes that should have been picked up. I will be using this branch on my project to see if anything goes wrong.

But, with this branch, lens-rs never recompiles, my changes to optics seem to be picked up, and incremental compilation works as expected.

### CODE REVIEW

**Comment by maackle** [comment]
Improvements could include collecting optics from different crates separately (each `section` returned by `inwelling()` appears to be a different crate). But this is already a huge improvement if it works.

**Comment by TOETOE55** [comment]
Amazing! Thank you very much for your Pull Request! After some verification, we would like to merge it into our codebase. I really appreciate your contribution and have learned something new from your PR.

**Comment by maackle** [comment]
Thank you for your efforts to bring optics to Rust! I hope to help where I can

**Comment by maackle** [comment]
BTW, I am already seeing this acting unreliably in my project, so it needs some work.

**Comment by TOETOE55** [comment]
I'm not very familiar with the mechanics of cargo yet(e.g. build script), I need some time to learn. XD

**Comment by maackle** [comment]
Apparently I'm not either, since this doesn't work ;)

I misinterpreted "rerun-if-changed". That sets up the rerun rules for every future compilation, for the build script itself. I thought the build script would always run, and "rerun" was referring to compiling the entire crate, but that's not the case, so this PR actually causes the build script to not run when it should.

I'm not sure that this approach will work, so feel free to close this unless you see some way to make it work.

**Comment by TOETOE55** [comment]
https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/How.20to.20recompile.20after.20the.20generated.20code.20has.20changed/near/363991604 
What a pity. It seems that cargo cannot do it at present.

**Pull request closed without merging**
